//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Receiver.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/MobiCarta", ConfigurationName="WebService.MobiCartaWebServiceSoap")]
    public interface MobiCartaWebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idClient del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/clientStatus", ReplyAction="*")]
        Receiver.WebService.clientStatusResponse clientStatus(Receiver.WebService.clientStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clientStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clientStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.WebService.clientStatusRequestBody Body;
        
        public clientStatusRequest() {
        }
        
        public clientStatusRequest(Receiver.WebService.clientStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class clientStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idClient;
        
        public clientStatusRequestBody() {
        }
        
        public clientStatusRequestBody(string idClient) {
            this.idClient = idClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class clientStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="clientStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.WebService.clientStatusResponseBody Body;
        
        public clientStatusResponse() {
        }
        
        public clientStatusResponse(Receiver.WebService.clientStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class clientStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int clientStatusResult;
        
        public clientStatusResponseBody() {
        }
        
        public clientStatusResponseBody(int clientStatusResult) {
            this.clientStatusResult = clientStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobiCartaWebServiceSoapChannel : Receiver.WebService.MobiCartaWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobiCartaWebServiceSoapClient : System.ServiceModel.ClientBase<Receiver.WebService.MobiCartaWebServiceSoap>, Receiver.WebService.MobiCartaWebServiceSoap {
        
        public MobiCartaWebServiceSoapClient() {
        }
        
        public MobiCartaWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobiCartaWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.WebService.clientStatusResponse Receiver.WebService.MobiCartaWebServiceSoap.clientStatus(Receiver.WebService.clientStatusRequest request) {
            return base.Channel.clientStatus(request);
        }
        
        public int clientStatus(string idClient) {
            Receiver.WebService.clientStatusRequest inValue = new Receiver.WebService.clientStatusRequest();
            inValue.Body = new Receiver.WebService.clientStatusRequestBody();
            inValue.Body.idClient = idClient;
            Receiver.WebService.clientStatusResponse retVal = ((Receiver.WebService.MobiCartaWebServiceSoap)(this)).clientStatus(inValue);
            return retVal.Body.clientStatusResult;
        }
    }
}
