//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Receiver.webServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/MobiCarta", ConfigurationName="webServer.MobiCartaWebServicesSoap")]
    public interface MobiCartaWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/connect", ReplyAction="*")]
        bool connect();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getRoomsResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getRooms", ReplyAction="*")]
        Receiver.webServer.getRoomsResponse getRooms(Receiver.webServer.getRoomsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getRoom", ReplyAction="*")]
        Receiver.webServer.getRoomResponse getRoom(Receiver.webServer.getRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/saveRoom", ReplyAction="*")]
        Receiver.webServer.saveRoomResponse saveRoom(Receiver.webServer.saveRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getTablesStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTablesStatus", ReplyAction="*")]
        Receiver.webServer.getTablesStatusResponse getTablesStatus(Receiver.webServer.getTablesStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento room del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/resetJourney", ReplyAction="*")]
        Receiver.webServer.resetJourneyResponse resetJourney(Receiver.webServer.resetJourneyRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getClientStatus", ReplyAction="*")]
        Receiver.webServer.getClientStatusResponse getClientStatus(Receiver.webServer.getClientStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setAllocationTable", ReplyAction="*")]
        Receiver.webServer.setAllocationTableResponse setAllocationTable(Receiver.webServer.setAllocationTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento setDeallocationTableResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setDeallocationTable", ReplyAction="*")]
        Receiver.webServer.setDeallocationTableResponse setDeallocationTable(Receiver.webServer.setDeallocationTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setDeallocationClient", ReplyAction="*")]
        Receiver.webServer.setDeallocationClientResponse setDeallocationClient(Receiver.webServer.setDeallocationClientRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getProductsResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getProducts", ReplyAction="*")]
        Receiver.webServer.getProductsResponse getProducts(Receiver.webServer.getProductsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getOrdersStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getOrdersStatus", ReplyAction="*")]
        Receiver.webServer.getOrdersStatusResponse getOrdersStatus(Receiver.webServer.getOrdersStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getTableStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTableStatus", ReplyAction="*")]
        Receiver.webServer.getTableStatusResponse getTableStatus(Receiver.webServer.getTableStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bill del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/addBillPaid", ReplyAction="*")]
        Receiver.webServer.addBillPaidResponse addBillPaid(Receiver.webServer.addBillPaidRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/addNewOrder", ReplyAction="*")]
        Receiver.webServer.addNewOrderResponse addNewOrder(Receiver.webServer.addNewOrderRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento product del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setOrderStatus", ReplyAction="*")]
        Receiver.webServer.setOrderStatusResponse setOrderStatus(Receiver.webServer.setOrderStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento product del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setProductAmount", ReplyAction="*")]
        Receiver.webServer.setProductAmountResponse setProductAmount(Receiver.webServer.setProductAmountRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTableID", ReplyAction="*")]
        Receiver.webServer.getTableIDResponse getTableID(Receiver.webServer.getTableIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRooms", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomsRequestBody Body;
        
        public getRoomsRequest() {
        }
        
        public getRoomsRequest(Receiver.webServer.getRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getRoomsRequestBody {
        
        public getRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomsResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomsResponseBody Body;
        
        public getRoomsResponse() {
        }
        
        public getRoomsResponse(Receiver.webServer.getRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRoomsResult;
        
        public getRoomsResponseBody() {
        }
        
        public getRoomsResponseBody(string getRoomsResult) {
            this.getRoomsResult = getRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoom", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomRequestBody Body;
        
        public getRoomRequest() {
        }
        
        public getRoomRequest(Receiver.webServer.getRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getRoomRequestBody() {
        }
        
        public getRoomRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomResponseBody Body;
        
        public getRoomResponse() {
        }
        
        public getRoomResponse(Receiver.webServer.getRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRoomResult;
        
        public getRoomResponseBody() {
        }
        
        public getRoomResponseBody(string getRoomResult) {
            this.getRoomResult = getRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveRoom", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.saveRoomRequestBody Body;
        
        public saveRoomRequest() {
        }
        
        public saveRoomRequest(Receiver.webServer.saveRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class saveRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public saveRoomRequestBody() {
        }
        
        public saveRoomRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveRoomResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.saveRoomResponseBody Body;
        
        public saveRoomResponse() {
        }
        
        public saveRoomResponse(Receiver.webServer.saveRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class saveRoomResponseBody {
        
        public saveRoomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTablesStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTablesStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTablesStatusRequestBody Body;
        
        public getTablesStatusRequest() {
        }
        
        public getTablesStatusRequest(Receiver.webServer.getTablesStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getTablesStatusRequestBody {
        
        public getTablesStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTablesStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTablesStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTablesStatusResponseBody Body;
        
        public getTablesStatusResponse() {
        }
        
        public getTablesStatusResponse(Receiver.webServer.getTablesStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTablesStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTablesStatusResult;
        
        public getTablesStatusResponseBody() {
        }
        
        public getTablesStatusResponseBody(string getTablesStatusResult) {
            this.getTablesStatusResult = getTablesStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetJourneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetJourney", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.resetJourneyRequestBody Body;
        
        public resetJourneyRequest() {
        }
        
        public resetJourneyRequest(Receiver.webServer.resetJourneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class resetJourneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string room;
        
        public resetJourneyRequestBody() {
        }
        
        public resetJourneyRequestBody(string room) {
            this.room = room;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetJourneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetJourneyResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.resetJourneyResponseBody Body;
        
        public resetJourneyResponse() {
        }
        
        public resetJourneyResponse(Receiver.webServer.resetJourneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class resetJourneyResponseBody {
        
        public resetJourneyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientStatusRequestBody Body;
        
        public getClientStatusRequest() {
        }
        
        public getClientStatusRequest(Receiver.webServer.getClientStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string surname;
        
        public getClientStatusRequestBody() {
        }
        
        public getClientStatusRequestBody(string dni, string name, string surname) {
            this.dni = dni;
            this.name = name;
            this.surname = surname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientStatusResponseBody Body;
        
        public getClientStatusResponse() {
        }
        
        public getClientStatusResponse(Receiver.webServer.getClientStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getClientStatusResult;
        
        public getClientStatusResponseBody() {
        }
        
        public getClientStatusResponseBody(int getClientStatusResult) {
            this.getClientStatusResult = getClientStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setAllocationTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setAllocationTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setAllocationTableRequestBody Body;
        
        public setAllocationTableRequest() {
        }
        
        public setAllocationTableRequest(Receiver.webServer.setAllocationTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setAllocationTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int guests;
        
        public setAllocationTableRequestBody() {
        }
        
        public setAllocationTableRequestBody(string dni, int tableID, int guests) {
            this.dni = dni;
            this.tableID = tableID;
            this.guests = guests;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setAllocationTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setAllocationTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setAllocationTableResponseBody Body;
        
        public setAllocationTableResponse() {
        }
        
        public setAllocationTableResponse(Receiver.webServer.setAllocationTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setAllocationTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setAllocationTableResult;
        
        public setAllocationTableResponseBody() {
        }
        
        public setAllocationTableResponseBody(string setAllocationTableResult) {
            this.setAllocationTableResult = setAllocationTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationTableRequestBody Body;
        
        public setDeallocationTableRequest() {
        }
        
        public setDeallocationTableRequest(Receiver.webServer.setDeallocationTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        public setDeallocationTableRequestBody() {
        }
        
        public setDeallocationTableRequestBody(int tableID) {
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationTableResponseBody Body;
        
        public setDeallocationTableResponse() {
        }
        
        public setDeallocationTableResponse(Receiver.webServer.setDeallocationTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeallocationTableResult;
        
        public setDeallocationTableResponseBody() {
        }
        
        public setDeallocationTableResponseBody(string setDeallocationTableResult) {
            this.setDeallocationTableResult = setDeallocationTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationClient", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationClientRequestBody Body;
        
        public setDeallocationClientRequest() {
        }
        
        public setDeallocationClientRequest(Receiver.webServer.setDeallocationClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public setDeallocationClientRequestBody() {
        }
        
        public setDeallocationClientRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationClientResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationClientResponseBody Body;
        
        public setDeallocationClientResponse() {
        }
        
        public setDeallocationClientResponse(Receiver.webServer.setDeallocationClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeallocationClientResult;
        
        public setDeallocationClientResponseBody() {
        }
        
        public setDeallocationClientResponseBody(string setDeallocationClientResult) {
            this.setDeallocationClientResult = setDeallocationClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProducts", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getProductsRequestBody Body;
        
        public getProductsRequest() {
        }
        
        public getProductsRequest(Receiver.webServer.getProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getProductsRequestBody {
        
        public getProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductsResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getProductsResponseBody Body;
        
        public getProductsResponse() {
        }
        
        public getProductsResponse(Receiver.webServer.getProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProductsResult;
        
        public getProductsResponseBody() {
        }
        
        public getProductsResponseBody(string getProductsResult) {
            this.getProductsResult = getProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrdersStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrdersStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getOrdersStatusRequestBody Body;
        
        public getOrdersStatusRequest() {
        }
        
        public getOrdersStatusRequest(Receiver.webServer.getOrdersStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getOrdersStatusRequestBody {
        
        public getOrdersStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrdersStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrdersStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getOrdersStatusResponseBody Body;
        
        public getOrdersStatusResponse() {
        }
        
        public getOrdersStatusResponse(Receiver.webServer.getOrdersStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getOrdersStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getOrdersStatusResult;
        
        public getOrdersStatusResponseBody() {
        }
        
        public getOrdersStatusResponseBody(string getOrdersStatusResult) {
            this.getOrdersStatusResult = getOrdersStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableStatusRequestBody Body;
        
        public getTableStatusRequest() {
        }
        
        public getTableStatusRequest(Receiver.webServer.getTableStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        public getTableStatusRequestBody() {
        }
        
        public getTableStatusRequestBody(int tableID) {
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableStatusResponseBody Body;
        
        public getTableStatusResponse() {
        }
        
        public getTableStatusResponse(Receiver.webServer.getTableStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTableStatusResult;
        
        public getTableStatusResponseBody() {
        }
        
        public getTableStatusResponseBody(string getTableStatusResult) {
            this.getTableStatusResult = getTableStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBillPaidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBillPaid", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.addBillPaidRequestBody Body;
        
        public addBillPaidRequest() {
        }
        
        public addBillPaidRequest(Receiver.webServer.addBillPaidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addBillPaidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bill;
        
        public addBillPaidRequestBody() {
        }
        
        public addBillPaidRequestBody(string bill) {
            this.bill = bill;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBillPaidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addBillPaidResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.addBillPaidResponseBody Body;
        
        public addBillPaidResponse() {
        }
        
        public addBillPaidResponse(Receiver.webServer.addBillPaidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addBillPaidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addBillPaidResult;
        
        public addBillPaidResponseBody() {
        }
        
        public addBillPaidResponseBody(string addBillPaidResult) {
            this.addBillPaidResult = addBillPaidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewOrder", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.addNewOrderRequestBody Body;
        
        public addNewOrderRequest() {
        }
        
        public addNewOrderRequest(Receiver.webServer.addNewOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addNewOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public addNewOrderRequestBody() {
        }
        
        public addNewOrderRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewOrderResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.addNewOrderResponseBody Body;
        
        public addNewOrderResponse() {
        }
        
        public addNewOrderResponse(Receiver.webServer.addNewOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addNewOrderResponseBody {
        
        public addNewOrderResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setOrderStatusRequestBody Body;
        
        public setOrderStatusRequest() {
        }
        
        public setOrderStatusRequest(Receiver.webServer.setOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string product;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int status;
        
        public setOrderStatusRequestBody() {
        }
        
        public setOrderStatusRequestBody(int tableID, string product, string date, int status) {
            this.tableID = tableID;
            this.product = product;
            this.date = date;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setOrderStatusResponseBody Body;
        
        public setOrderStatusResponse() {
        }
        
        public setOrderStatusResponse(Receiver.webServer.setOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setOrderStatusResponseBody {
        
        public setOrderStatusResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setProductAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setProductAmount", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setProductAmountRequestBody Body;
        
        public setProductAmountRequest() {
        }
        
        public setProductAmountRequest(Receiver.webServer.setProductAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setProductAmountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string product;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int amount;
        
        public setProductAmountRequestBody() {
        }
        
        public setProductAmountRequestBody(int tableID, string product, string date, int amount) {
            this.tableID = tableID;
            this.product = product;
            this.date = date;
            this.amount = amount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setProductAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setProductAmountResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setProductAmountResponseBody Body;
        
        public setProductAmountResponse() {
        }
        
        public setProductAmountResponse(Receiver.webServer.setProductAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setProductAmountResponseBody {
        
        public setProductAmountResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableID", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableIDRequestBody Body;
        
        public getTableIDRequest() {
        }
        
        public getTableIDRequest(Receiver.webServer.getTableIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public getTableIDRequestBody() {
        }
        
        public getTableIDRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableIDResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableIDResponseBody Body;
        
        public getTableIDResponse() {
        }
        
        public getTableIDResponse(Receiver.webServer.getTableIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getTableIDResult;
        
        public getTableIDResponseBody() {
        }
        
        public getTableIDResponseBody(int getTableIDResult) {
            this.getTableIDResult = getTableIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobiCartaWebServicesSoapChannel : Receiver.webServer.MobiCartaWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobiCartaWebServicesSoapClient : System.ServiceModel.ClientBase<Receiver.webServer.MobiCartaWebServicesSoap>, Receiver.webServer.MobiCartaWebServicesSoap {
        
        public MobiCartaWebServicesSoapClient() {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool connect() {
            return base.Channel.connect();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getRoomsResponse Receiver.webServer.MobiCartaWebServicesSoap.getRooms(Receiver.webServer.getRoomsRequest request) {
            return base.Channel.getRooms(request);
        }
        
        public string getRooms() {
            Receiver.webServer.getRoomsRequest inValue = new Receiver.webServer.getRoomsRequest();
            inValue.Body = new Receiver.webServer.getRoomsRequestBody();
            Receiver.webServer.getRoomsResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getRooms(inValue);
            return retVal.Body.getRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getRoomResponse Receiver.webServer.MobiCartaWebServicesSoap.getRoom(Receiver.webServer.getRoomRequest request) {
            return base.Channel.getRoom(request);
        }
        
        public string getRoom(string name) {
            Receiver.webServer.getRoomRequest inValue = new Receiver.webServer.getRoomRequest();
            inValue.Body = new Receiver.webServer.getRoomRequestBody();
            inValue.Body.name = name;
            Receiver.webServer.getRoomResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getRoom(inValue);
            return retVal.Body.getRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.saveRoomResponse Receiver.webServer.MobiCartaWebServicesSoap.saveRoom(Receiver.webServer.saveRoomRequest request) {
            return base.Channel.saveRoom(request);
        }
        
        public void saveRoom(string xml) {
            Receiver.webServer.saveRoomRequest inValue = new Receiver.webServer.saveRoomRequest();
            inValue.Body = new Receiver.webServer.saveRoomRequestBody();
            inValue.Body.xml = xml;
            Receiver.webServer.saveRoomResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).saveRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getTablesStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getTablesStatus(Receiver.webServer.getTablesStatusRequest request) {
            return base.Channel.getTablesStatus(request);
        }
        
        public string getTablesStatus() {
            Receiver.webServer.getTablesStatusRequest inValue = new Receiver.webServer.getTablesStatusRequest();
            inValue.Body = new Receiver.webServer.getTablesStatusRequestBody();
            Receiver.webServer.getTablesStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getTablesStatus(inValue);
            return retVal.Body.getTablesStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.resetJourneyResponse Receiver.webServer.MobiCartaWebServicesSoap.resetJourney(Receiver.webServer.resetJourneyRequest request) {
            return base.Channel.resetJourney(request);
        }
        
        public void resetJourney(string room) {
            Receiver.webServer.resetJourneyRequest inValue = new Receiver.webServer.resetJourneyRequest();
            inValue.Body = new Receiver.webServer.resetJourneyRequestBody();
            inValue.Body.room = room;
            Receiver.webServer.resetJourneyResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).resetJourney(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getClientStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getClientStatus(Receiver.webServer.getClientStatusRequest request) {
            return base.Channel.getClientStatus(request);
        }
        
        public int getClientStatus(string dni, string name, string surname) {
            Receiver.webServer.getClientStatusRequest inValue = new Receiver.webServer.getClientStatusRequest();
            inValue.Body = new Receiver.webServer.getClientStatusRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            Receiver.webServer.getClientStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getClientStatus(inValue);
            return retVal.Body.getClientStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setAllocationTableResponse Receiver.webServer.MobiCartaWebServicesSoap.setAllocationTable(Receiver.webServer.setAllocationTableRequest request) {
            return base.Channel.setAllocationTable(request);
        }
        
        public string setAllocationTable(string dni, int tableID, int guests) {
            Receiver.webServer.setAllocationTableRequest inValue = new Receiver.webServer.setAllocationTableRequest();
            inValue.Body = new Receiver.webServer.setAllocationTableRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.tableID = tableID;
            inValue.Body.guests = guests;
            Receiver.webServer.setAllocationTableResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setAllocationTable(inValue);
            return retVal.Body.setAllocationTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setDeallocationTableResponse Receiver.webServer.MobiCartaWebServicesSoap.setDeallocationTable(Receiver.webServer.setDeallocationTableRequest request) {
            return base.Channel.setDeallocationTable(request);
        }
        
        public string setDeallocationTable(int tableID) {
            Receiver.webServer.setDeallocationTableRequest inValue = new Receiver.webServer.setDeallocationTableRequest();
            inValue.Body = new Receiver.webServer.setDeallocationTableRequestBody();
            inValue.Body.tableID = tableID;
            Receiver.webServer.setDeallocationTableResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setDeallocationTable(inValue);
            return retVal.Body.setDeallocationTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setDeallocationClientResponse Receiver.webServer.MobiCartaWebServicesSoap.setDeallocationClient(Receiver.webServer.setDeallocationClientRequest request) {
            return base.Channel.setDeallocationClient(request);
        }
        
        public string setDeallocationClient(string dni) {
            Receiver.webServer.setDeallocationClientRequest inValue = new Receiver.webServer.setDeallocationClientRequest();
            inValue.Body = new Receiver.webServer.setDeallocationClientRequestBody();
            inValue.Body.dni = dni;
            Receiver.webServer.setDeallocationClientResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setDeallocationClient(inValue);
            return retVal.Body.setDeallocationClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getProductsResponse Receiver.webServer.MobiCartaWebServicesSoap.getProducts(Receiver.webServer.getProductsRequest request) {
            return base.Channel.getProducts(request);
        }
        
        public string getProducts() {
            Receiver.webServer.getProductsRequest inValue = new Receiver.webServer.getProductsRequest();
            inValue.Body = new Receiver.webServer.getProductsRequestBody();
            Receiver.webServer.getProductsResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getProducts(inValue);
            return retVal.Body.getProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getOrdersStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getOrdersStatus(Receiver.webServer.getOrdersStatusRequest request) {
            return base.Channel.getOrdersStatus(request);
        }
        
        public string getOrdersStatus() {
            Receiver.webServer.getOrdersStatusRequest inValue = new Receiver.webServer.getOrdersStatusRequest();
            inValue.Body = new Receiver.webServer.getOrdersStatusRequestBody();
            Receiver.webServer.getOrdersStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getOrdersStatus(inValue);
            return retVal.Body.getOrdersStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getTableStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getTableStatus(Receiver.webServer.getTableStatusRequest request) {
            return base.Channel.getTableStatus(request);
        }
        
        public string getTableStatus(int tableID) {
            Receiver.webServer.getTableStatusRequest inValue = new Receiver.webServer.getTableStatusRequest();
            inValue.Body = new Receiver.webServer.getTableStatusRequestBody();
            inValue.Body.tableID = tableID;
            Receiver.webServer.getTableStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getTableStatus(inValue);
            return retVal.Body.getTableStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.addBillPaidResponse Receiver.webServer.MobiCartaWebServicesSoap.addBillPaid(Receiver.webServer.addBillPaidRequest request) {
            return base.Channel.addBillPaid(request);
        }
        
        public string addBillPaid(string bill) {
            Receiver.webServer.addBillPaidRequest inValue = new Receiver.webServer.addBillPaidRequest();
            inValue.Body = new Receiver.webServer.addBillPaidRequestBody();
            inValue.Body.bill = bill;
            Receiver.webServer.addBillPaidResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).addBillPaid(inValue);
            return retVal.Body.addBillPaidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.addNewOrderResponse Receiver.webServer.MobiCartaWebServicesSoap.addNewOrder(Receiver.webServer.addNewOrderRequest request) {
            return base.Channel.addNewOrder(request);
        }
        
        public void addNewOrder(string xml) {
            Receiver.webServer.addNewOrderRequest inValue = new Receiver.webServer.addNewOrderRequest();
            inValue.Body = new Receiver.webServer.addNewOrderRequestBody();
            inValue.Body.xml = xml;
            Receiver.webServer.addNewOrderResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).addNewOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setOrderStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.setOrderStatus(Receiver.webServer.setOrderStatusRequest request) {
            return base.Channel.setOrderStatus(request);
        }
        
        public void setOrderStatus(int tableID, string product, string date, int status) {
            Receiver.webServer.setOrderStatusRequest inValue = new Receiver.webServer.setOrderStatusRequest();
            inValue.Body = new Receiver.webServer.setOrderStatusRequestBody();
            inValue.Body.tableID = tableID;
            inValue.Body.product = product;
            inValue.Body.date = date;
            inValue.Body.status = status;
            Receiver.webServer.setOrderStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setOrderStatus(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setProductAmountResponse Receiver.webServer.MobiCartaWebServicesSoap.setProductAmount(Receiver.webServer.setProductAmountRequest request) {
            return base.Channel.setProductAmount(request);
        }
        
        public void setProductAmount(int tableID, string product, string date, int amount) {
            Receiver.webServer.setProductAmountRequest inValue = new Receiver.webServer.setProductAmountRequest();
            inValue.Body = new Receiver.webServer.setProductAmountRequestBody();
            inValue.Body.tableID = tableID;
            inValue.Body.product = product;
            inValue.Body.date = date;
            inValue.Body.amount = amount;
            Receiver.webServer.setProductAmountResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setProductAmount(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getTableIDResponse Receiver.webServer.MobiCartaWebServicesSoap.getTableID(Receiver.webServer.getTableIDRequest request) {
            return base.Channel.getTableID(request);
        }
        
        public int getTableID(string dni) {
            Receiver.webServer.getTableIDRequest inValue = new Receiver.webServer.getTableIDRequest();
            inValue.Body = new Receiver.webServer.getTableIDRequestBody();
            inValue.Body.dni = dni;
            Receiver.webServer.getTableIDResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getTableID(inValue);
            return retVal.Body.getTableIDResult;
        }
    }
}
