//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Receiver.webServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/MobiCarta", ConfigurationName="webServer.MobiCartaWebServicesSoap")]
    public interface MobiCartaWebServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/connect", ReplyAction="*")]
        bool connect();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getRoomsResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getRooms", ReplyAction="*")]
        Receiver.webServer.getRoomsResponse getRooms(Receiver.webServer.getRoomsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getRoom", ReplyAction="*")]
        Receiver.webServer.getRoomResponse getRoom(Receiver.webServer.getRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/saveRoom", ReplyAction="*")]
        Receiver.webServer.saveRoomResponse saveRoom(Receiver.webServer.saveRoomRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getTablesStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTablesStatus", ReplyAction="*")]
        Receiver.webServer.getTablesStatusResponse getTablesStatus(Receiver.webServer.getTablesStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTableID", ReplyAction="*")]
        Receiver.webServer.getTableIDResponse getTableID(Receiver.webServer.getTableIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento client del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getClientHistory", ReplyAction="*")]
        Receiver.webServer.getClientHistoryResponse getClientHistory(Receiver.webServer.getClientHistoryRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getClientsHistoryResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getClientsHistory", ReplyAction="*")]
        Receiver.webServer.getClientsHistoryResponse getClientsHistory(Receiver.webServer.getClientsHistoryRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento room del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/resetJourney", ReplyAction="*")]
        Receiver.webServer.resetJourneyResponse resetJourney(Receiver.webServer.resetJourneyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/resetDB", ReplyAction="*")]
        void resetDB();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xmlClient del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getClientStatus", ReplyAction="*")]
        Receiver.webServer.getClientStatusResponse getClientStatus(Receiver.webServer.getClientStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getBillAmount", ReplyAction="*")]
        double getBillAmount(int tableID);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setAllocationTable", ReplyAction="*")]
        Receiver.webServer.setAllocationTableResponse setAllocationTable(Receiver.webServer.setAllocationTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento setDeallocationTableResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setDeallocationTable", ReplyAction="*")]
        Receiver.webServer.setDeallocationTableResponse setDeallocationTable(Receiver.webServer.setDeallocationTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento dni del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setDeallocationClient", ReplyAction="*")]
        Receiver.webServer.setDeallocationClientResponse setDeallocationClient(Receiver.webServer.setDeallocationClientRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setRestaurantInfo", ReplyAction="*")]
        Receiver.webServer.setRestaurantInfoResponse setRestaurantInfo(Receiver.webServer.setRestaurantInfoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/saveProductsList", ReplyAction="*")]
        Receiver.webServer.saveProductsListResponse saveProductsList(Receiver.webServer.saveProductsListRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getProductsResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getProducts", ReplyAction="*")]
        Receiver.webServer.getProductsResponse getProducts(Receiver.webServer.getProductsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getOrdersStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getOrdersStatus", ReplyAction="*")]
        Receiver.webServer.getOrdersStatusResponse getOrdersStatus(Receiver.webServer.getOrdersStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getTableStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getTableStatus", ReplyAction="*")]
        Receiver.webServer.getTableStatusResponse getTableStatus(Receiver.webServer.getTableStatusRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento xml del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/addNewOrder", ReplyAction="*")]
        Receiver.webServer.addNewOrderResponse addNewOrder(Receiver.webServer.addNewOrderRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento setOrderStatusResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setOrderStatus", ReplyAction="*")]
        Receiver.webServer.setOrderStatusResponse setOrderStatus(Receiver.webServer.setOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setProductAmount", ReplyAction="*")]
        void setProductAmount(int orderID, int amount);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento setOrderTableResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/setOrderTable", ReplyAction="*")]
        Receiver.webServer.setOrderTableResponse setOrderTable(Receiver.webServer.setOrderTableRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getBillResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/getBill", ReplyAction="*")]
        Receiver.webServer.getBillResponse getBill(Receiver.webServer.getBillRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento payBillResult del espacio de nombres http://localhost/MobiCarta no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/MobiCarta/payBill", ReplyAction="*")]
        Receiver.webServer.payBillResponse payBill(Receiver.webServer.payBillRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRooms", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomsRequestBody Body;
        
        public getRoomsRequest() {
        }
        
        public getRoomsRequest(Receiver.webServer.getRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getRoomsRequestBody {
        
        public getRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomsResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomsResponseBody Body;
        
        public getRoomsResponse() {
        }
        
        public getRoomsResponse(Receiver.webServer.getRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRoomsResult;
        
        public getRoomsResponseBody() {
        }
        
        public getRoomsResponseBody(string getRoomsResult) {
            this.getRoomsResult = getRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoom", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomRequestBody Body;
        
        public getRoomRequest() {
        }
        
        public getRoomRequest(Receiver.webServer.getRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getRoomRequestBody() {
        }
        
        public getRoomRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRoomResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getRoomResponseBody Body;
        
        public getRoomResponse() {
        }
        
        public getRoomResponse(Receiver.webServer.getRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRoomResult;
        
        public getRoomResponseBody() {
        }
        
        public getRoomResponseBody(string getRoomResult) {
            this.getRoomResult = getRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveRoom", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.saveRoomRequestBody Body;
        
        public saveRoomRequest() {
        }
        
        public saveRoomRequest(Receiver.webServer.saveRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class saveRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public saveRoomRequestBody() {
        }
        
        public saveRoomRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveRoomResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.saveRoomResponseBody Body;
        
        public saveRoomResponse() {
        }
        
        public saveRoomResponse(Receiver.webServer.saveRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class saveRoomResponseBody {
        
        public saveRoomResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTablesStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTablesStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTablesStatusRequestBody Body;
        
        public getTablesStatusRequest() {
        }
        
        public getTablesStatusRequest(Receiver.webServer.getTablesStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getTablesStatusRequestBody {
        
        public getTablesStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTablesStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTablesStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTablesStatusResponseBody Body;
        
        public getTablesStatusResponse() {
        }
        
        public getTablesStatusResponse(Receiver.webServer.getTablesStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTablesStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTablesStatusResult;
        
        public getTablesStatusResponseBody() {
        }
        
        public getTablesStatusResponseBody(string getTablesStatusResult) {
            this.getTablesStatusResult = getTablesStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableID", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableIDRequestBody Body;
        
        public getTableIDRequest() {
        }
        
        public getTableIDRequest(Receiver.webServer.getTableIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public getTableIDRequestBody() {
        }
        
        public getTableIDRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableIDResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableIDResponseBody Body;
        
        public getTableIDResponse() {
        }
        
        public getTableIDResponse(Receiver.webServer.getTableIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getTableIDResult;
        
        public getTableIDResponseBody() {
        }
        
        public getTableIDResponseBody(int getTableIDResult) {
            this.getTableIDResult = getTableIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientHistory", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientHistoryRequestBody Body;
        
        public getClientHistoryRequest() {
        }
        
        public getClientHistoryRequest(Receiver.webServer.getClientHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string client;
        
        public getClientHistoryRequestBody() {
        }
        
        public getClientHistoryRequestBody(string client) {
            this.client = client;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientHistoryResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientHistoryResponseBody Body;
        
        public getClientHistoryResponse() {
        }
        
        public getClientHistoryResponse(Receiver.webServer.getClientHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getClientHistoryResult;
        
        public getClientHistoryResponseBody() {
        }
        
        public getClientHistoryResponseBody(string getClientHistoryResult) {
            this.getClientHistoryResult = getClientHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientsHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientsHistory", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientsHistoryRequestBody Body;
        
        public getClientsHistoryRequest() {
        }
        
        public getClientsHistoryRequest(Receiver.webServer.getClientsHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getClientsHistoryRequestBody {
        
        public getClientsHistoryRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientsHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientsHistoryResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientsHistoryResponseBody Body;
        
        public getClientsHistoryResponse() {
        }
        
        public getClientsHistoryResponse(Receiver.webServer.getClientsHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientsHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getClientsHistoryResult;
        
        public getClientsHistoryResponseBody() {
        }
        
        public getClientsHistoryResponseBody(string getClientsHistoryResult) {
            this.getClientsHistoryResult = getClientsHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetJourneyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetJourney", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.resetJourneyRequestBody Body;
        
        public resetJourneyRequest() {
        }
        
        public resetJourneyRequest(Receiver.webServer.resetJourneyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class resetJourneyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string room;
        
        public resetJourneyRequestBody() {
        }
        
        public resetJourneyRequestBody(string room) {
            this.room = room;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class resetJourneyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="resetJourneyResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.resetJourneyResponseBody Body;
        
        public resetJourneyResponse() {
        }
        
        public resetJourneyResponse(Receiver.webServer.resetJourneyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class resetJourneyResponseBody {
        
        public resetJourneyResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientStatusRequestBody Body;
        
        public getClientStatusRequest() {
        }
        
        public getClientStatusRequest(Receiver.webServer.getClientStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlClient;
        
        public getClientStatusRequestBody() {
        }
        
        public getClientStatusRequestBody(string xmlClient) {
            this.xmlClient = xmlClient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClientStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClientStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getClientStatusResponseBody Body;
        
        public getClientStatusResponse() {
        }
        
        public getClientStatusResponse(Receiver.webServer.getClientStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getClientStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getClientStatusResult;
        
        public getClientStatusResponseBody() {
        }
        
        public getClientStatusResponseBody(int getClientStatusResult) {
            this.getClientStatusResult = getClientStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setAllocationTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setAllocationTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setAllocationTableRequestBody Body;
        
        public setAllocationTableRequest() {
        }
        
        public setAllocationTableRequest(Receiver.webServer.setAllocationTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setAllocationTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tableID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int guests;
        
        public setAllocationTableRequestBody() {
        }
        
        public setAllocationTableRequestBody(string dni, int tableID, int guests) {
            this.dni = dni;
            this.tableID = tableID;
            this.guests = guests;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setAllocationTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setAllocationTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setAllocationTableResponseBody Body;
        
        public setAllocationTableResponse() {
        }
        
        public setAllocationTableResponse(Receiver.webServer.setAllocationTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setAllocationTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setAllocationTableResult;
        
        public setAllocationTableResponseBody() {
        }
        
        public setAllocationTableResponseBody(string setAllocationTableResult) {
            this.setAllocationTableResult = setAllocationTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationTableRequestBody Body;
        
        public setDeallocationTableRequest() {
        }
        
        public setDeallocationTableRequest(Receiver.webServer.setDeallocationTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        public setDeallocationTableRequestBody() {
        }
        
        public setDeallocationTableRequestBody(int tableID) {
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationTableResponseBody Body;
        
        public setDeallocationTableResponse() {
        }
        
        public setDeallocationTableResponse(Receiver.webServer.setDeallocationTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeallocationTableResult;
        
        public setDeallocationTableResponseBody() {
        }
        
        public setDeallocationTableResponseBody(string setDeallocationTableResult) {
            this.setDeallocationTableResult = setDeallocationTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationClient", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationClientRequestBody Body;
        
        public setDeallocationClientRequest() {
        }
        
        public setDeallocationClientRequest(Receiver.webServer.setDeallocationClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dni;
        
        public setDeallocationClientRequestBody() {
        }
        
        public setDeallocationClientRequestBody(string dni) {
            this.dni = dni;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setDeallocationClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setDeallocationClientResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setDeallocationClientResponseBody Body;
        
        public setDeallocationClientResponse() {
        }
        
        public setDeallocationClientResponse(Receiver.webServer.setDeallocationClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setDeallocationClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setDeallocationClientResult;
        
        public setDeallocationClientResponseBody() {
        }
        
        public setDeallocationClientResponseBody(string setDeallocationClientResult) {
            this.setDeallocationClientResult = setDeallocationClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRestaurantInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRestaurantInfo", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setRestaurantInfoRequestBody Body;
        
        public setRestaurantInfoRequest() {
        }
        
        public setRestaurantInfoRequest(Receiver.webServer.setRestaurantInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setRestaurantInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public setRestaurantInfoRequestBody() {
        }
        
        public setRestaurantInfoRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setRestaurantInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setRestaurantInfoResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setRestaurantInfoResponseBody Body;
        
        public setRestaurantInfoResponse() {
        }
        
        public setRestaurantInfoResponse(Receiver.webServer.setRestaurantInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class setRestaurantInfoResponseBody {
        
        public setRestaurantInfoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveProductsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveProductsList", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.saveProductsListRequestBody Body;
        
        public saveProductsListRequest() {
        }
        
        public saveProductsListRequest(Receiver.webServer.saveProductsListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class saveProductsListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public saveProductsListRequestBody() {
        }
        
        public saveProductsListRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class saveProductsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="saveProductsListResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.saveProductsListResponseBody Body;
        
        public saveProductsListResponse() {
        }
        
        public saveProductsListResponse(Receiver.webServer.saveProductsListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class saveProductsListResponseBody {
        
        public saveProductsListResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProducts", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getProductsRequestBody Body;
        
        public getProductsRequest() {
        }
        
        public getProductsRequest(Receiver.webServer.getProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getProductsRequestBody {
        
        public getProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductsResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getProductsResponseBody Body;
        
        public getProductsResponse() {
        }
        
        public getProductsResponse(Receiver.webServer.getProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProductsResult;
        
        public getProductsResponseBody() {
        }
        
        public getProductsResponseBody(string getProductsResult) {
            this.getProductsResult = getProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrdersStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrdersStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getOrdersStatusRequestBody Body;
        
        public getOrdersStatusRequest() {
        }
        
        public getOrdersStatusRequest(Receiver.webServer.getOrdersStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getOrdersStatusRequestBody {
        
        public getOrdersStatusRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrdersStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrdersStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getOrdersStatusResponseBody Body;
        
        public getOrdersStatusResponse() {
        }
        
        public getOrdersStatusResponse(Receiver.webServer.getOrdersStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getOrdersStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getOrdersStatusResult;
        
        public getOrdersStatusResponseBody() {
        }
        
        public getOrdersStatusResponseBody(string getOrdersStatusResult) {
            this.getOrdersStatusResult = getOrdersStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableStatusRequestBody Body;
        
        public getTableStatusRequest() {
        }
        
        public getTableStatusRequest(Receiver.webServer.getTableStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        public getTableStatusRequestBody() {
        }
        
        public getTableStatusRequestBody(int tableID) {
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTableStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTableStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getTableStatusResponseBody Body;
        
        public getTableStatusResponse() {
        }
        
        public getTableStatusResponse(Receiver.webServer.getTableStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getTableStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTableStatusResult;
        
        public getTableStatusResponseBody() {
        }
        
        public getTableStatusResponseBody(string getTableStatusResult) {
            this.getTableStatusResult = getTableStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewOrder", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.addNewOrderRequestBody Body;
        
        public addNewOrderRequest() {
        }
        
        public addNewOrderRequest(Receiver.webServer.addNewOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addNewOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public addNewOrderRequestBody() {
        }
        
        public addNewOrderRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNewOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNewOrderResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.addNewOrderResponseBody Body;
        
        public addNewOrderResponse() {
        }
        
        public addNewOrderResponse(Receiver.webServer.addNewOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class addNewOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addNewOrderResult;
        
        public addNewOrderResponseBody() {
        }
        
        public addNewOrderResponseBody(string addNewOrderResult) {
            this.addNewOrderResult = addNewOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderStatus", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setOrderStatusRequestBody Body;
        
        public setOrderStatusRequest() {
        }
        
        public setOrderStatusRequest(Receiver.webServer.setOrderStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int status;
        
        public setOrderStatusRequestBody() {
        }
        
        public setOrderStatusRequestBody(int orderID, int status) {
            this.orderID = orderID;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderStatusResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setOrderStatusResponseBody Body;
        
        public setOrderStatusResponse() {
        }
        
        public setOrderStatusResponse(Receiver.webServer.setOrderStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setOrderStatusResult;
        
        public setOrderStatusResponseBody() {
        }
        
        public setOrderStatusResponseBody(string setOrderStatusResult) {
            this.setOrderStatusResult = setOrderStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderTableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderTable", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setOrderTableRequestBody Body;
        
        public setOrderTableRequest() {
        }
        
        public setOrderTableRequest(Receiver.webServer.setOrderTableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderTableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int tableID;
        
        public setOrderTableRequestBody() {
        }
        
        public setOrderTableRequestBody(int orderID, int tableID) {
            this.orderID = orderID;
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setOrderTableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setOrderTableResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.setOrderTableResponseBody Body;
        
        public setOrderTableResponse() {
        }
        
        public setOrderTableResponse(Receiver.webServer.setOrderTableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class setOrderTableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string setOrderTableResult;
        
        public setOrderTableResponseBody() {
        }
        
        public setOrderTableResponseBody(string setOrderTableResult) {
            this.setOrderTableResult = setOrderTableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBill", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getBillRequestBody Body;
        
        public getBillRequest() {
        }
        
        public getBillRequest(Receiver.webServer.getBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int tableID;
        
        public getBillRequestBody() {
        }
        
        public getBillRequestBody(int tableID) {
            this.tableID = tableID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBillResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.getBillResponseBody Body;
        
        public getBillResponse() {
        }
        
        public getBillResponse(Receiver.webServer.getBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class getBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getBillResult;
        
        public getBillResponseBody() {
        }
        
        public getBillResponseBody(string getBillResult) {
            this.getBillResult = getBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class payBillRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="payBill", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.payBillRequestBody Body;
        
        public payBillRequest() {
        }
        
        public payBillRequest(Receiver.webServer.payBillRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class payBillRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int billID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int type;
        
        public payBillRequestBody() {
        }
        
        public payBillRequestBody(int billID, int type) {
            this.billID = billID;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class payBillResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="payBillResponse", Namespace="http://localhost/MobiCarta", Order=0)]
        public Receiver.webServer.payBillResponseBody Body;
        
        public payBillResponse() {
        }
        
        public payBillResponse(Receiver.webServer.payBillResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/MobiCarta")]
    public partial class payBillResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string payBillResult;
        
        public payBillResponseBody() {
        }
        
        public payBillResponseBody(string payBillResult) {
            this.payBillResult = payBillResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobiCartaWebServicesSoapChannel : Receiver.webServer.MobiCartaWebServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobiCartaWebServicesSoapClient : System.ServiceModel.ClientBase<Receiver.webServer.MobiCartaWebServicesSoap>, Receiver.webServer.MobiCartaWebServicesSoap {
        
        public MobiCartaWebServicesSoapClient() {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobiCartaWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool connect() {
            return base.Channel.connect();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getRoomsResponse Receiver.webServer.MobiCartaWebServicesSoap.getRooms(Receiver.webServer.getRoomsRequest request) {
            return base.Channel.getRooms(request);
        }
        
        public string getRooms() {
            Receiver.webServer.getRoomsRequest inValue = new Receiver.webServer.getRoomsRequest();
            inValue.Body = new Receiver.webServer.getRoomsRequestBody();
            Receiver.webServer.getRoomsResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getRooms(inValue);
            return retVal.Body.getRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getRoomResponse Receiver.webServer.MobiCartaWebServicesSoap.getRoom(Receiver.webServer.getRoomRequest request) {
            return base.Channel.getRoom(request);
        }
        
        public string getRoom(string name) {
            Receiver.webServer.getRoomRequest inValue = new Receiver.webServer.getRoomRequest();
            inValue.Body = new Receiver.webServer.getRoomRequestBody();
            inValue.Body.name = name;
            Receiver.webServer.getRoomResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getRoom(inValue);
            return retVal.Body.getRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.saveRoomResponse Receiver.webServer.MobiCartaWebServicesSoap.saveRoom(Receiver.webServer.saveRoomRequest request) {
            return base.Channel.saveRoom(request);
        }
        
        public void saveRoom(string xml) {
            Receiver.webServer.saveRoomRequest inValue = new Receiver.webServer.saveRoomRequest();
            inValue.Body = new Receiver.webServer.saveRoomRequestBody();
            inValue.Body.xml = xml;
            Receiver.webServer.saveRoomResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).saveRoom(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getTablesStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getTablesStatus(Receiver.webServer.getTablesStatusRequest request) {
            return base.Channel.getTablesStatus(request);
        }
        
        public string getTablesStatus() {
            Receiver.webServer.getTablesStatusRequest inValue = new Receiver.webServer.getTablesStatusRequest();
            inValue.Body = new Receiver.webServer.getTablesStatusRequestBody();
            Receiver.webServer.getTablesStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getTablesStatus(inValue);
            return retVal.Body.getTablesStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getTableIDResponse Receiver.webServer.MobiCartaWebServicesSoap.getTableID(Receiver.webServer.getTableIDRequest request) {
            return base.Channel.getTableID(request);
        }
        
        public int getTableID(string dni) {
            Receiver.webServer.getTableIDRequest inValue = new Receiver.webServer.getTableIDRequest();
            inValue.Body = new Receiver.webServer.getTableIDRequestBody();
            inValue.Body.dni = dni;
            Receiver.webServer.getTableIDResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getTableID(inValue);
            return retVal.Body.getTableIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getClientHistoryResponse Receiver.webServer.MobiCartaWebServicesSoap.getClientHistory(Receiver.webServer.getClientHistoryRequest request) {
            return base.Channel.getClientHistory(request);
        }
        
        public string getClientHistory(string client) {
            Receiver.webServer.getClientHistoryRequest inValue = new Receiver.webServer.getClientHistoryRequest();
            inValue.Body = new Receiver.webServer.getClientHistoryRequestBody();
            inValue.Body.client = client;
            Receiver.webServer.getClientHistoryResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getClientHistory(inValue);
            return retVal.Body.getClientHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getClientsHistoryResponse Receiver.webServer.MobiCartaWebServicesSoap.getClientsHistory(Receiver.webServer.getClientsHistoryRequest request) {
            return base.Channel.getClientsHistory(request);
        }
        
        public string getClientsHistory() {
            Receiver.webServer.getClientsHistoryRequest inValue = new Receiver.webServer.getClientsHistoryRequest();
            inValue.Body = new Receiver.webServer.getClientsHistoryRequestBody();
            Receiver.webServer.getClientsHistoryResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getClientsHistory(inValue);
            return retVal.Body.getClientsHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.resetJourneyResponse Receiver.webServer.MobiCartaWebServicesSoap.resetJourney(Receiver.webServer.resetJourneyRequest request) {
            return base.Channel.resetJourney(request);
        }
        
        public void resetJourney(string room) {
            Receiver.webServer.resetJourneyRequest inValue = new Receiver.webServer.resetJourneyRequest();
            inValue.Body = new Receiver.webServer.resetJourneyRequestBody();
            inValue.Body.room = room;
            Receiver.webServer.resetJourneyResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).resetJourney(inValue);
        }
        
        public void resetDB() {
            base.Channel.resetDB();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getClientStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getClientStatus(Receiver.webServer.getClientStatusRequest request) {
            return base.Channel.getClientStatus(request);
        }
        
        public int getClientStatus(string xmlClient) {
            Receiver.webServer.getClientStatusRequest inValue = new Receiver.webServer.getClientStatusRequest();
            inValue.Body = new Receiver.webServer.getClientStatusRequestBody();
            inValue.Body.xmlClient = xmlClient;
            Receiver.webServer.getClientStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getClientStatus(inValue);
            return retVal.Body.getClientStatusResult;
        }
        
        public double getBillAmount(int tableID) {
            return base.Channel.getBillAmount(tableID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setAllocationTableResponse Receiver.webServer.MobiCartaWebServicesSoap.setAllocationTable(Receiver.webServer.setAllocationTableRequest request) {
            return base.Channel.setAllocationTable(request);
        }
        
        public string setAllocationTable(string dni, int tableID, int guests) {
            Receiver.webServer.setAllocationTableRequest inValue = new Receiver.webServer.setAllocationTableRequest();
            inValue.Body = new Receiver.webServer.setAllocationTableRequestBody();
            inValue.Body.dni = dni;
            inValue.Body.tableID = tableID;
            inValue.Body.guests = guests;
            Receiver.webServer.setAllocationTableResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setAllocationTable(inValue);
            return retVal.Body.setAllocationTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setDeallocationTableResponse Receiver.webServer.MobiCartaWebServicesSoap.setDeallocationTable(Receiver.webServer.setDeallocationTableRequest request) {
            return base.Channel.setDeallocationTable(request);
        }
        
        public string setDeallocationTable(int tableID) {
            Receiver.webServer.setDeallocationTableRequest inValue = new Receiver.webServer.setDeallocationTableRequest();
            inValue.Body = new Receiver.webServer.setDeallocationTableRequestBody();
            inValue.Body.tableID = tableID;
            Receiver.webServer.setDeallocationTableResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setDeallocationTable(inValue);
            return retVal.Body.setDeallocationTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setDeallocationClientResponse Receiver.webServer.MobiCartaWebServicesSoap.setDeallocationClient(Receiver.webServer.setDeallocationClientRequest request) {
            return base.Channel.setDeallocationClient(request);
        }
        
        public string setDeallocationClient(string dni) {
            Receiver.webServer.setDeallocationClientRequest inValue = new Receiver.webServer.setDeallocationClientRequest();
            inValue.Body = new Receiver.webServer.setDeallocationClientRequestBody();
            inValue.Body.dni = dni;
            Receiver.webServer.setDeallocationClientResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setDeallocationClient(inValue);
            return retVal.Body.setDeallocationClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setRestaurantInfoResponse Receiver.webServer.MobiCartaWebServicesSoap.setRestaurantInfo(Receiver.webServer.setRestaurantInfoRequest request) {
            return base.Channel.setRestaurantInfo(request);
        }
        
        public void setRestaurantInfo(string xml) {
            Receiver.webServer.setRestaurantInfoRequest inValue = new Receiver.webServer.setRestaurantInfoRequest();
            inValue.Body = new Receiver.webServer.setRestaurantInfoRequestBody();
            inValue.Body.xml = xml;
            Receiver.webServer.setRestaurantInfoResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setRestaurantInfo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.saveProductsListResponse Receiver.webServer.MobiCartaWebServicesSoap.saveProductsList(Receiver.webServer.saveProductsListRequest request) {
            return base.Channel.saveProductsList(request);
        }
        
        public void saveProductsList(string xml) {
            Receiver.webServer.saveProductsListRequest inValue = new Receiver.webServer.saveProductsListRequest();
            inValue.Body = new Receiver.webServer.saveProductsListRequestBody();
            inValue.Body.xml = xml;
            Receiver.webServer.saveProductsListResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).saveProductsList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getProductsResponse Receiver.webServer.MobiCartaWebServicesSoap.getProducts(Receiver.webServer.getProductsRequest request) {
            return base.Channel.getProducts(request);
        }
        
        public string getProducts() {
            Receiver.webServer.getProductsRequest inValue = new Receiver.webServer.getProductsRequest();
            inValue.Body = new Receiver.webServer.getProductsRequestBody();
            Receiver.webServer.getProductsResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getProducts(inValue);
            return retVal.Body.getProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getOrdersStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getOrdersStatus(Receiver.webServer.getOrdersStatusRequest request) {
            return base.Channel.getOrdersStatus(request);
        }
        
        public string getOrdersStatus() {
            Receiver.webServer.getOrdersStatusRequest inValue = new Receiver.webServer.getOrdersStatusRequest();
            inValue.Body = new Receiver.webServer.getOrdersStatusRequestBody();
            Receiver.webServer.getOrdersStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getOrdersStatus(inValue);
            return retVal.Body.getOrdersStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getTableStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.getTableStatus(Receiver.webServer.getTableStatusRequest request) {
            return base.Channel.getTableStatus(request);
        }
        
        public string getTableStatus(int tableID) {
            Receiver.webServer.getTableStatusRequest inValue = new Receiver.webServer.getTableStatusRequest();
            inValue.Body = new Receiver.webServer.getTableStatusRequestBody();
            inValue.Body.tableID = tableID;
            Receiver.webServer.getTableStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getTableStatus(inValue);
            return retVal.Body.getTableStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.addNewOrderResponse Receiver.webServer.MobiCartaWebServicesSoap.addNewOrder(Receiver.webServer.addNewOrderRequest request) {
            return base.Channel.addNewOrder(request);
        }
        
        public string addNewOrder(string xml) {
            Receiver.webServer.addNewOrderRequest inValue = new Receiver.webServer.addNewOrderRequest();
            inValue.Body = new Receiver.webServer.addNewOrderRequestBody();
            inValue.Body.xml = xml;
            Receiver.webServer.addNewOrderResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).addNewOrder(inValue);
            return retVal.Body.addNewOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setOrderStatusResponse Receiver.webServer.MobiCartaWebServicesSoap.setOrderStatus(Receiver.webServer.setOrderStatusRequest request) {
            return base.Channel.setOrderStatus(request);
        }
        
        public string setOrderStatus(int orderID, int status) {
            Receiver.webServer.setOrderStatusRequest inValue = new Receiver.webServer.setOrderStatusRequest();
            inValue.Body = new Receiver.webServer.setOrderStatusRequestBody();
            inValue.Body.orderID = orderID;
            inValue.Body.status = status;
            Receiver.webServer.setOrderStatusResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setOrderStatus(inValue);
            return retVal.Body.setOrderStatusResult;
        }
        
        public void setProductAmount(int orderID, int amount) {
            base.Channel.setProductAmount(orderID, amount);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.setOrderTableResponse Receiver.webServer.MobiCartaWebServicesSoap.setOrderTable(Receiver.webServer.setOrderTableRequest request) {
            return base.Channel.setOrderTable(request);
        }
        
        public string setOrderTable(int orderID, int tableID) {
            Receiver.webServer.setOrderTableRequest inValue = new Receiver.webServer.setOrderTableRequest();
            inValue.Body = new Receiver.webServer.setOrderTableRequestBody();
            inValue.Body.orderID = orderID;
            inValue.Body.tableID = tableID;
            Receiver.webServer.setOrderTableResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).setOrderTable(inValue);
            return retVal.Body.setOrderTableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.getBillResponse Receiver.webServer.MobiCartaWebServicesSoap.getBill(Receiver.webServer.getBillRequest request) {
            return base.Channel.getBill(request);
        }
        
        public string getBill(int tableID) {
            Receiver.webServer.getBillRequest inValue = new Receiver.webServer.getBillRequest();
            inValue.Body = new Receiver.webServer.getBillRequestBody();
            inValue.Body.tableID = tableID;
            Receiver.webServer.getBillResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).getBill(inValue);
            return retVal.Body.getBillResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Receiver.webServer.payBillResponse Receiver.webServer.MobiCartaWebServicesSoap.payBill(Receiver.webServer.payBillRequest request) {
            return base.Channel.payBill(request);
        }
        
        public string payBill(int billID, int type) {
            Receiver.webServer.payBillRequest inValue = new Receiver.webServer.payBillRequest();
            inValue.Body = new Receiver.webServer.payBillRequestBody();
            inValue.Body.billID = billID;
            inValue.Body.type = type;
            Receiver.webServer.payBillResponse retVal = ((Receiver.webServer.MobiCartaWebServicesSoap)(this)).payBill(inValue);
            return retVal.Body.payBillResult;
        }
    }
}
